### PR TITLE
[WIP] Update Armagetron to 0.2.9.1.0 and runtime to 20.08

### PR DESCRIPTION
**Pull request by AsciiWolf**
/cc @bilelmoussaoui

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Hmm, this will need more work. The desktop/icon/appdata files are now installed during make install, however there are some issues with them. I will update this PR after I fix them.

**edit:** Ignore what I said, the upstream files are probably fine, I just have to make a patch adding OARS metadata and releases to the AppData file. I will also contribute the OARS metadata to upstream.

**Comment by AsciiWolf** [comment]
> I will also contribute the OARS metadata to upstream.

https://gitlab.com/armagetronad/armagetronad/-/merge_requests/101

**Comment by AsciiWolf** [comment]
The Desktop/AppData/Icon files seem to be installed to a wrong locations for some reason. See the [upstream ticket](https://gitlab.com/armagetronad/armagetronad/-/issues/73).

**Comment by zmanuel** [comment]
Picking this up in #5, thanks for the good start!

**Pull request closed without merging**
