### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
From the AppStream metadata validation: `errors":["appstream-missing-icon-file"]`

@zmanuel Any idea?

**Comment by AsciiWolf** [comment]
https://github.com/flathub/org.armagetronad.ArmagetronAdvanced/blob/master/org.armagetronad.ArmagetronAdvanced.json#L61

This could be the problem. Ideally, the AppStream metadata file should not be duplicated.

**Comment by AsciiWolf** [comment]
I apologize, but I give up. The current desktop (.desktop, icon, .appdata.xml) files process is completely wrong and should be fixed.

The post-install section should be changed as can be seen in my [second commit](https://github.com/flathub/org.armagetronad.ArmagetronAdvanced/pull/10/commits/2ad3fa2f58c4dc2bd2528a465f7df7f59ac6343a) and desktop files renaming should be handled directly by flatpak-builder or directly by the Armagetron Advanced source archive and/or Makefile.

The game works fine with the older runtime, so I will close this PR for now. @zmanuel Feel free to prepare the PR (and fix the desktop files) yourself. Let me know if you have any questions, I will try to help, but I sadly don't have enough free time to properly work on all this myself. Sorry.

**Comment by zmanuel** [comment]
No worries, I'll handle this sometime. Thanks for your time!

**Comment by zmanuel** [comment]
Oh wait, I already did, but only for the current alpha branch in our private repository: https://gitlab.com/armagetronad/org-armagetronad-ArmagetronAdvanced/-/commit/4d9cd01274528ca739c1457c9612dda9149d73da
I did not get any build errors, dunno why; there were changes to the desktop directory, but mostly for macOS stuff. Getting metadata correct is black magic to me.

**Pull request closed without merging**
