### PR TITLE
Update the runtime to 22.08

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
bot, build

**Comment by zmanuel** [comment]
Most likely, the verification stumbles over the http to https redirect. I changed the URIs to https upstream and as a patch in the separate PR #8 .

**Comment by zmanuel** [comment]
bot, build

**Comment by zmanuel** [comment]
Ah. I thought the test build would be done with the branches merged. Apparently not.

**Comment by AsciiWolf** [comment]
bot, build

**Pull request merged**
